logging:
  level:
    root: info
    com.example.springbatch: debug

spring:
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/r102?serverTimezone=Asia/Seoul
    username: root
    password: 1234